services:
  db:
    image: postgres:15-alpine
    container_name: small_gastro_db_day_closing
    environment:
      POSTGRES_DB: small_gastro
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data_dev_day_closing:/var/lib/postgresql/data
    ports:
      - "5460:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d small_gastro"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_dev_day_closing:
